version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    platform: linux/amd64
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
